---
- name: Apply Kubernetes YAML files locally
  hosts: localhost
  gather_facts: false
  become: true
  vars:
    ansible_become_user: jaimin
    ansible_become_password: "Jaimin@@0822"
  tasks:
    - name: Check current user
      command: whoami
      register: current_user

    - name: Display the current user
      debug:
        var: current_user.stdout