---
- name: Run tasks as a different user
  hosts: localhost
  become: yes
  become_user: jaimin
  vars:
    ansible_become_password: "Jaimin@@0822"
  tasks:
    - name: Check current user
      command: whoami
      register: whoami_output

    - name: Print current user
      debug:
        msg: "Running as: {{ whoami_output.stdout }}"