---
- name: Apply Kubernetes YAML files
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Check if kubectl is installed
      command: kubectl version --kubeconfig=/home/jaimin/.kube/config